public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!!!");
        var box = 5;
        System.out.println(box);
        box = box + 2;
        System.out.println(box);
        box = box - 3;
        System.out.println(box);
        box = box * 3;
        System.out.println(box);
        box = box / 4;
        System.out.println(box);
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        dog = dog + 4;
        System.out.println(dog);
        cat = cat + 4;
        System.out.println(cat);
        paper = paper + 4;
        System.out.println(paper);
        dog = dog - 3.5;
        System.out.println(dog);
        cat = cat - 1.6;
        System.out.println(cat);
        paper = paper - 7639;
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend - 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        var mass1 = 78.2;
        System.out.println(mass1);
        var mass2 = 82.7;
        System.out.println(mass2);
        var total = mass1 + mass2;
        System.out.println(total);
        var difference = mass2 - mass1;
        System.out.println(difference);
        var surplus = mass2 % mass1;
        System.out.println(surplus);
        var totalHours = 640;
        System.out.println(totalHours);
        var workDay = 8;
        System.out.println(workDay);
        var totally = totalHours / workDay;
        System.out.println("Всего в компании работает" + " " + totally + " " + "человек");
        var totallyNew = totally + 94;
        System.out.println(totallyNew);
        var hoursNew = totallyNew * workDay;
        System.out.println("Если в компании работает" + " " + totallyNew + " " + "человека, то всего" + " " + hoursNew + " " + "часов работы может быть поделено между сотрудниками!!!");
    }
}
